# Generated by Django 4.1.7 on 2023-02-16 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_country_id_airlinecompany_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='airline_company',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='destination_country',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='origin_country',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='type',
        ),
        migrations.AddField(
            model_name='flight',
            name='ticket_economy_price',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AirlineCompany',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AddField(
            model_name='flight',
            name='destination_airport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='app.airport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='origin_airport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='app.airport'),
            preserve_default=False,
        ),
    ]
