# Generated by Django 4.1.7 on 2023-03-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_flight_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline_company',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='airline_company_code',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
