# Generated by Django 4.1.7 on 2023-03-26 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_flight_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='city_code',
        ),
    ]
