# Generated by Django 4.1.7 on 2023-03-31 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_flight_airline_company_flight_airline_company_code'),
        ('app', '0004_remove_airport_city_code'),
    ]

    operations = [
    ]
