# Generated by Django 4.1.7 on 2023-02-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_name_airport_airport_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='display_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
