# Generated by Django 4.1.7 on 2023-02-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_airport_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price_manual_override',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='remaining_tickets_manual_override',
            field=models.BooleanField(default=0),
        ),
    ]
