# Generated by Django 4.1.7 on 2023-02-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_flight_price_manual_override_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='price_manual_override',
        ),
        migrations.AddField(
            model_name='flight',
            name='ticket_economy_manual_override',
            field=models.BooleanField(default=0),
        ),
    ]
